[project]
name = "bbos-daemon-dataset"
version = "0.0.0"
requires-python = "==3.11.*"
dependencies = [
  "bbos",
  "numpy==2.4.6",
  "posix-ipc==1.3.2",
]

[tool.uv.sources]
bbos = { path = "../../..", editable = true }

[build-system]
requires = ["setuptools==80.9.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []
packages = []
