from bbos import register, realtime, state
import numpy as np
from pathlib import Path
from .ik import get_ik_solver

# ============================================================================
# Configs
# ============================================================================
@register
class arm_left:
    # --- Hardware & motor constants -----------------------------------------
    port = "/dev/ttyARMLEFT"
    baudrate = 1000000
    motors = [1, 2, 3, 4, 5, 6, 7, 8]
    dof = len(motors)
    read_only = False
    kg_cm_to_nm = 0.0980665
    kt_3950 = 0.204
    # Motors 2,3,4 (array idx 1,2,3 = joints j1/j2/j3) are ST-3120-C001 coreless servos.
    # Datasheet Kt is 25.5 kg.cm/A = 2.50 Nm/A.
    kt_st3120 = 25.5 * kg_cm_to_nm
    kt = [kt_3950, kt_st3120, kt_st3120, kt_st3120, kt_3950, kt_3950, kt_3950, kt_3950]
    st3120_mask = np.array([False, True, True, True, False, False, False, False], dtype=np.bool_)
    # The left gripper motor is mounted mirror-reversed vs the right arm
    # (it turns the opposite way for the same physical open/close). Every
    # other joint sign now lives in the URDF; only this one stays in code,
    # applied to the gripper setpoint in teleop (the gripper is not IK-driven).
    gripper_sign = -1

    # --- Position control ---------------------------------------------------
    Kp = [32] * dof
    Kd = [32] * dof
    Ki = [10] * dof
    # J0 (vertical stage) daemon-side software integrator — drives the steady-state
    # hold error to ~0, which the servo firmware I-term can't.
    # J0 only; engages only while the J0 setpoint is ~stationary so moves don't wind it up.
    j0_integ_ki = 10.0      # integral gain (1/s) on J0 position error; 0 disables
    j0_integ_clamp = 0.05  # anti-windup: max |goal-position bias| (turns)
    j0_integ_gate = 5e-4   # engage only when |delta commanded J0 pos| < this per control tick
    j0_integ_band = 0.02   # engage only when |J0 position error| < this (turns); rejects transients
    # J7 (gripper, index 7 = "LG") current-relief loop — position-mode outer loop that keeps a
    # held grasp from overheating. When the jaw is held still (|vel| < vel_stop for hold_time) and
    # drawing more than i_hold, it walks the Goal_Position toward the actual position to shrink the
    # servo error, shedding the current (hence heat) down to i_hold; if current falls below i_hold
    # (grip slipping), it relaxes the backoff to re-grip. Reset on (re)enable / new command.
    j7_relief_enable = True     # enable the J7 current-relief loop
    j7_relief_vel_stop = 0.02   # turns/s; |vel| below this = jaw held still
    j7_relief_hold_time = 0.3   # s held before relieving (debounce vs mid-move zero-crossings)
    j7_relief_i_hold = 1.5      # A target holding current (gentle grip); TUNE on hardware
    j7_relief_db = 0.5          # A deadband around i_hold (avoids chatter)
    j7_relief_step = 5e-4       # turns/tick goal nudge (slow; ~0.075 turns/s at 150 Hz)
    j7_relief_bias_max = 0.1    # turns; max backoff from the commanded goal (safety)
    j7_relief_gate = 5e-3       # turns; commanded-goal change > this = new grasp -> reset relief
    j7_relief_debug = True      # throttled [j7relief] diagnostic print (cmd/act/bias/goal/cur/stall/vel)
    #Kpd = [0] * dof
    #Kdd = [0.042] * dof
    angle_resolution = [1] * dof
    return_delay_time = [0] * dof
    acceleration = [254] * dof
    operating_mode = [0] * dof
    dt = 1.0 / 150  # 150 Hz
    wheel_radius = 0.0465 # gear radius of vertical stage
    # Per-joint EMA smoothing on commanded position (pos_filtered = alpha*cmd + (1-alpha)*prev).
    # Higher alpha = less smoothing, faster tracking. J2/J3 (ST-3120) are less filtered so they
    # keep up with teleop commands; rest of the arm keeps the prior 0.2 smoothing.
    lpf_alpha = np.array([0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2], dtype=np.float32)
    max_pos_diff = 0.01
    interp_duration = 0.05

    # --- Kinematics (URDF / IK) ---------------------------------------------
    # The current CAD-accurate model, generated by the bb-urdf repo. Replaces the
    # old bb-models/bb1, whose link lengths were up to 24 mm off (j1-j2 was
    # 43.6 mm vs the real 67.5 mm), worth ~65 mm of end-effector error.
    # It lives here, tracked by bbos, rather than in the nested bb-models
    # checkout -- so a plain `git pull` on develop is all anyone needs.
    urdf_path = str(Path(__file__).parent / "urdf" / "robot.urdf")
    ik_solver = get_ik_solver(
        solver_name="hybrid_ik",
        urdf_content=Path(Path(__file__).parent / "urdf/robot.urdf").read_text(),
        base_link="arm_base",
        tolerances=[0.005]*3 + [0.01]*3,
        starting_config=[0.0]*7,
        joint_centering_weight=0.1,
        rik_max_iterations=5,
        # Per-joint centering stiffness (j0..j6). Mast hold and two-seed
        # recovery are Rust-side defaults in hybrid_ik.
        centering_weights=[50.0, 25.0, 15.0, 5.0, 10.0, 12.0, 1.5],
    )
    # j3 nominal is the home elbow angle: q2urdf(CFG.home)[3] is +1.571 on both arms.
    ik = ik_solver(ee_link="left_eef", nominal_config=[0, 0.0, 0.0, 1.5708, 0.0, 0.0, 0.0])
    # URDF joint names (bb_v2 numbers the carriage j0, so LJ1..LJ7 -> lj0..lj6).
    # daemon.py / impedance_controller look these up in the Pinocchio model by name.
    joint_names = ["lj0", "lj1", "lj2", "lj3", "lj4", "lj5", "lj6", "left_left_gripper"]
    # bb1 carried each joint's direction in its URDF <axis>; bb_v2 normalises every
    # axis to +Z (required -- qp_ik and ranged_ik snap axes to principal directions),
    # so the direction moves here instead. Applied in q2urdf/urdf2q, which is already
    # the motor<->URDF boundary. Derived by fitting bb1 FK against bb_v2 FK over the
    # workspace, then VERIFIED joint-by-joint on bracketbot-092 with view_arms.py --control:
    # every joint moves the same direction as the viser model.
    ik_sign = np.array([-1, 1, -1, 1, 1, -1, -1], dtype=np.float32)

    # --- Zeroing & calibration ----------------------------------------------
    j0_increment = -6/4096  # 6 encoder ticks; sign is the "up" (toward top stop) direction
    j0_cal_step = 0.002  # per-tick step (turns) for easing J0 down off the top stop in calibrate
    cal_step = 0.001
    j1_cal_clearance = 0.1  # extra J1 offset held during the auto self-cal so the arm clears itself (cal pose only; not CFG.home)

    # --- J0 (lift) torque-mode homing ---------------------------------------
    # J0 homes by driving UP into the top hardstop under constant torque (current mode) until it
    # stops moving (velocity ~0) for j0_cal_settle_s, then sets the zero j0_top_offset_turns
    # BELOW the stop so the lift never rests on the hardstop (that back-off point becomes J0
    # max). Shared by the daemon startup homing and calibrate.py.
    j0_cal_tau = 1.5             # Nm pressing up into the stop (must beat gravity + stiction)
    j0_cal_tau_start = 1.0       # Nm at ramp start (above gravity so it starts lifting smoothly)
    j0_cal_ramp_s = 1.0          # s to ramp torque start -> full (gentler approach)
    j0_top_offset_turns = 0.02   # zero/max sits this far below the top hardstop (turns)
    j0_cal_settle_s = 2.0        # s of ~zero motion (pressed at the stop) before the top is accepted
    j0_cal_vel_stop = 0.003      # turns/s; calibrate.py stall threshold on the daemon-filtered velocity
    j0_cal_move_eps_turns = 7e-4 # daemon stall: position must stay within this (~3 enc counts) for settle_s
    j0_cal_min_travel_turns = 0.02  # J0 must rise at least this far before a stall counts (rejects a false stall when torque can't lift)
    j0_cal_wrongdir_turns = 0.05    # abort homing if J0 runs this far the WRONG way (torque sign error / can't hold gravity)


    j0_homing_timeout_s = 8.0
    skip_startup_homing = False
    mode_settle_retries = 3

    # ========================================================================
    # Motor limits
    # ========================================================================
    # All firmware/daemon protection limits. No software joint-range
    # limits — firmware handles all position safety.
    # --- J0 homing current (hard-stop detection) ----------------------------
    j0_current_limit = 10.0

    # --- Current limits -----------------------------------------------------
    hls_safety_current_scale = 1.0     # normal HLS cap
    st3120_safety_current_scale = 1.25 # next test: 125% rated current cap on ST-3120 joints
    protection_current_3950 = 2031    # normal HLS value: ~13.2A (raw × 0.0065)
    protection_current_st3120 = 500   # ST-3120 firmware max: ~3.25A
    protection_current = np.array(
        [
            protection_current_3950,
            protection_current_st3120,
            protection_current_st3120,
            protection_current_st3120,
            protection_current_3950,
            protection_current_3950,
            protection_current_3950,
            protection_current_3950,
        ],
        dtype=np.uint16,
    )
    # Per-joint phase-current clamp (A), scaled down for position-control bring-up.
    hard_current_limit = np.array(
        [
            13.2 * hls_safety_current_scale,
            1.57 * st3120_safety_current_scale,
            1.57 * st3120_safety_current_scale,
            1.57 * st3120_safety_current_scale,
            13.2 * hls_safety_current_scale,
            13.2 * hls_safety_current_scale,
            13.2 * hls_safety_current_scale,
            13.2 * hls_safety_current_scale,
        ],
        dtype=np.float32,
    )
    sustained_current_scale = 0.76    # fraction of hard_current_limit for sustained-current trip (~10A for HLS)
    sustained_current_time_limit = 15.0  # seconds above sustained current threshold before trip
    current_slew_limit = 0.5    # max current change per iteration (A/tick) for torque mode
    # Sum-of-motor-currents cap for the new servo control board's 5 A supply rail.
    # Phase↔supply mapping on this board is not yet characterized, so budget below
    # the 5 A spec with margin. Intended enforcement: Σ|cs| < total_current_limit.
    # TODO(daemon): wire enforcement into arm_left daemon control loop.
    total_current_limit = 1.125 # A, sum across all 8 motors
    current_limit_cooldown_s = 1.0    # seconds to wait after current trip before re-enabling
    current_limit_interp_s = 3.0      # seconds to interpolate back to target after cooldown
    overcurrent_protection_time = 5   # ×10ms = 50ms overcurrent cooldown

    # --- Temperature limits -------------------------------------------------
    max_temperature = 55              # °C — firmware overtemp trip, auto-clears when cool
    software_temp_limit = 55          # °C — instant daemon-side temp trip
    sustained_temp_limit = 50         # °C — sustained temp threshold
    sustained_temp_time_limit = 15.0  # seconds above sustained_temp_limit before trip
    overtemp_cooldown_s = 30.0        # seconds to wait after temp trip before re-enabling
    temp_max_delta = 5.0              # max plausible °C change per tick (filter noise rejection)
    temp_stuck_ticks = 50            # consecutive finite-but-implausible reads before the temp filter re-seeds to raw, escaping a stuck value instead of locking forever (~0.75s at the 15ms state tick)

    # --- Torque limits ------------------------------------------------------
    # Gripper (J7) runs at a static SRAM Torque_Limit of 400 (firm enough to seat a grasp; the
    # J7 current-relief loop then sheds the holding current back down so it doesn't overheat);
    # the daemon raises it to gripper_cal_torque_limit only during calibration. Max_Torque_Limit
    # (EEPROM ceiling) is 1000 = 100% stall torque (register full scale) so the cal value is reachable.
    max_torque_limit = np.array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000], dtype=np.uint16)
    torque_limit = np.array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 300], dtype=np.uint16)

    # --- Velocity limit -----------------------------------------------------
    # Firmware Goal_Velocity register (uint16).
    goal_velocity = np.array([200, 4000, 4000, 4000, 200, 200, 200, 200], dtype=np.uint16)

    # --- Protection trip condition ------------------------------------------
    unloading_condition = 6           # bit1=overtemp + bit2=overcurrent → 0b110

    # ========================================================================
    # Control, compliance & gripper
    # ========================================================================
    # ST-3120 datasheet mode 2 is open-loop speed, not current mode.
    tau_mode_allowed = np.array([True, False, False, True, True, True, True, True], dtype=np.bool_)
    latency: float = 4.17
    latency_std: float = 0.38
    home = np.array([0,  0, 0, 0.25, 0, 0,  0, -0.15], dtype=np.float32)
    latency: float = 65.49
    latency_std: float = 53.65

    # --- Startup homing trajectory ------------------------------------------
    # On launch each arm is driven from its (likely untorqued) pose to home
    # along these waypoints (motor turns), flowing through them continuously
    # (Catmull-Rom) and resting only at home. CFG.home is appended by the
    # consumer; the right arm's waypoints are the negation of these (the arms
    # are mirror images in motor-turn space — see arm_right.startup_waypoints).
    startup_seg_durations = 1.25   # seconds per path segment (scalar)
    startup_waypoints = np.array([
        [0.329, -0.175, -0.15, 0.386, 0.049,  -0.04, 0.12, -0.011],
        [0.000, -0.0, -0.06, 0.386, 0.013,  -0.04, 0.0, -0.031]
    ], dtype=np.float32)

    # --- Compliance control -------------------------------------------------
    # admittance control via wrench estimation + spring-damper dynamics
    compliance_mass = 0.25
    compliance_kp_pos = 20.0
    compliance_kp_rot = 2.0
    compliance_force_reg = 1e-3
    compliance_torque_reg = 1e-2
    compliance_normal_axis = 2  # 0=x, 1=y, 2=z in EE frame
    ee_frame = "left_eef"

    # --- Gripper PD (current-mode, stiff) -----------------------------------
    gripper_kp = 15.0   # Nm/turn (high gain, tracks admittance ref)
    gripper_kd = 1.0    # Nm/(turn/s)
    gripper_mass = 0.05  # virtual mass (kg*turn^2)
    gripper_stiffness = 30.0  # virtual spring (Nm/turn)
    gripper_damping = 2.0  # virtual damper, ~2*sqrt(stiffness*mass) for critical damping
    gripper_compliance = False  # enable gripper admittance control
    # Gripper torque-limit during calibration. Normal operation holds the static
    # torque_limit[7] (300); the daemon raises the gripper to this higher value only while
    # calibrating so the open/close sweeps reach the stop-detection current without the gentle
    # static limit stalling them short.
    gripper_cal_torque_limit = 800        # SRAM Torque_Limit (raw, 0-1000) held during calibration

    @staticmethod
    def q2urdf(q):
        """motor positions (turns) -> URDF joint angles (radians/meters)"""
        q = q * (2 * np.pi)
        q[0] = q[0] * arm_left.wheel_radius
        q[7] = q[7] * arm_left.gripper_sign
        q[:7] = q[:7] * arm_left.ik_sign
        return q

    @staticmethod
    def urdf2q(urdf_pos):
        """URDF joint angles (radians/meters) -> motor positions (turns)"""
        q = urdf_pos.copy()
        q[:7] = q[:7] * arm_left.ik_sign          # sign is its own inverse
        q[0] = q[0] / arm_left.wheel_radius
        q[7] = q[7] * arm_left.gripper_sign
        q = q / (2 * np.pi)
        return q
# ============================================================================
# Types
# ============================================================================
@state
def arm_torque():
    return [("enable", np.bool_, arm_left.dof), ("tau_mode", np.bool_, arm_left.dof), ("compliance_mode", np.bool_, ()), ("axis_aligned", np.bool_, ()), ("force_only", np.bool_, ()), ("j0_homing", np.bool_, ()), ("calibrating", np.bool_, ())]

@realtime(ms=15)
def arm_ctrl():
    return [("pos", np.float32, arm_left.dof), ("vel", np.float32, arm_left.dof), ("tau", np.float32, arm_left.dof), ("alpha", np.float32, ())]

@realtime(ms=15)
def arm_state():
    return [("pos", np.float32, arm_left.dof), ("vel", np.float32, arm_left.dof), ("torque", np.float32, arm_left.dof), ("temp", np.float32, arm_left.dof), ("current", np.float32, arm_left.dof)]

# Pre-IK cartesian setpoint (the exact ik.solve() inputs, before IK -> joints).
# Cartesian twin of arm_ctrl; recorded by the dataset, not read by the arm daemon.
# `tracking` is True only while teleop is actively driving IK.
@realtime(ms=15)
def arm_target():
    return [("xyz", np.float32, (3,)), ("quat", np.float32, (4,)), ("grip", np.float32, ()), ("tracking", np.bool_, ())]
